version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - /opt/db/backup:/var/lib/postgresql/data/backup
      - /opt/db/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

networks:
  postgres:
    driver: bridge